remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: William Ortolá Leonard 
logo: /assets/img/Headshot.JPG
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: About Me
    url: /about
